version: '3'

services:
  frontend:
    build: 
      context: ./build
    ports:
      - '3000:3000'

  backend:
    build: 
      context: ./backend
    ports:
      - '8080:8080'
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql